config/routes.rb
BadgesEngine::Engine.routes.draw do
  resources :awards
  resources :badges
  resources :values
  resources :levels
end

app/models/badges_engine/award.rb
module BadgesEngine
  class Award < ActiveRecord::Base
    has_many :badges

    validates :title, presence: true
  end
end

app/models/badges_engine/badge.rb
module BadgesEngine
  class Badge < ActiveRecord::Base
    belongs_to :award
    belongs_to :value
    has_many :levels

    validates :name, presence: true, uniqueness: true

    accepts_nested_attributes_for :levels, allow_destroy: true

    mount_uploader :image, ImageUploader
  end
end

app/models/badges_engine/level.rb
module BadgesEngine
  class Level < ActiveRecord::Base
    belongs_to :badge
    after_initialize :default_tier

    validates :tier, numericality: { only_integer: true }

    private

    def default_tier
      self.tier ||= 1
    end
  end
end

app/models/badges_engine/value.rb
module BadgesEngine
  class Value < ActiveRecord::Base
    has_many :badges

    validates :name, presence: true, uniqueness: true
  end
end

app/controllers/badges_engine/application_controller.rb
module BadgesEngine
  class ApplicationController < ::ApplicationController
    if Rails.env.test?
      layout 'dummy'
    else
      layout 'admin'
    end
  end
end

app/controllers/badges_engine/awards_controller.rb
require_dependency "badges_engine/application_controller"

module BadgesEngine
  class AwardsController < ApplicationController
    before_action :set_award, only: [:show, :edit, :update, :destroy]

    def index
      @awards = Award.all
    end

    def show
    end

    def new
      @award = Award.new
    end

    def edit
    end

    def create
      @award = Award.new(award_params)
      if @award.save
        redirect_to @award, notice: 'Award was successfully created.'
      else
        render 'new'
      end
    end

    def update
      if @award.update(award_params)
        redirect_to @award, notice: 'Award was successfully updated.'
      else
        render 'edit'
      end
    end

    def destroy
      @award.destroy
      redirect_to awards_url, notice: 'Award was successfully destroyed.'
    end

    private

    def set_award
      @award = Award.find(params[:id])
    end

    def award_params
      params.require(:award).permit(:title, :description)
    end
  end
end

app/controllers/badges_engine/badges_controller.rb
require_dependency "badges_engine/application_controller"

module BadgesEngine
  class BadgesController < ApplicationController
    before_action :set_badge, only: [:show, :edit, :update, :destroy]
    helper_method :sort_column, :sort_direction

    def index
      @badges = if params[:search]
                Badge.where("name ILIKE ?", "%#{params[:search]}%")
                     .order(sort_column + " " + sort_direction)
             else
                Badge.order(sort_column + " " + sort_direction)
       end
    end

    def show
    end

    def new
      @badge = Badge.new
      @levels = @badge.levels.build
    end

    def edit
    end

    def create
      @badge = Badge.new(badge_params)
      if @badge.save
        redirect_to badges_url, notice: 'Badge was successfully created.'
      else
        render :new
      end
    end

    def update
      if @badge.update(badge_params)
        redirect_to badges_url, notice: 'Badge was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @badge.destroy
      redirect_to badges_url, notice: 'Badge was successfully destroyed.'
    end

    private

    def set_badge
      @badge = Badge.find(params[:id])
    end

    def badge_params
      params.require(:badge).permit(
        :name, :image, :description,
        :award_id, :value_id,
        levels_attributes: [ :id,
          :tier, :badge_alias, :badge_id, :_destroy
        ]
      )
    end

    def sort_column
      Badge.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
  end
end

app/controllers/badges_engine/levels_controller.rb
require_dependency "badges_engine/application_controller"

module BadgesEngine
  class LevelsController < ApplicationController
    before_action :set_level, only: [:show, :edit, :update, :destroy]

    def index
      @levels = Level.all
    end

    def show
    end

    def new
      @level = Level.new
    end

    def edit
    end

    def create
      @level = Level.new(level_params)
      if @level.save
        redirect_to @level, notice: 'level was successfully created.'
      else
        render 'new'
      end
    end

    def update
      if @level.update(level_params)
        redirect_to @level, notice: 'level was successfully updated.'
      else
        render 'edit'
      end
    end

    def destroy
      @level.destroy
      redirect_to levels_url, notice: 'level was successfully destroyed.'
    end

    private

    def set_level
      @level = Level.find(params[:id])
    end

    def level_params
      params.require(:level).permit(:badge_id , :tier, :badge_alias)
    end
  end
end

app/controllers/badges_engine/values_controller.rb
require_dependency "badges_engine/application_controller"

module BadgesEngine
  class ValuesController < ApplicationController
    before_action :set_value, only: [:show, :edit, :update, :destroy]

    def index
      @values = Value.all
    end

    def show
    end

    def new
      @value = Value.new
    end

    def edit
    end

    def create
      @value = Value.new(value_params)
      if @value.save
        redirect_to @value, notice: 'Value was successfully created.'
      else
        render :new
      end
    end

    def update
      if @value.update(value_params)
        redirect_to @value, notice: 'Value was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @value.destroy
      redirect_to values_url, notice: 'Value was successfully destroyed.'
    end

    private

    def set_value
      @value = Value.find(params[:id])
    end

    def value_params
      params.require(:value).permit(:name, :description)
    end
  end
end

app/helpers/badges_engine/application_helper.rb
module BadgesEngine
  module ApplicationHelper
    def method_missing method, *args, &block
      puts "LOOKING FOR ROUTES #{method}"
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          main_app.send(method, *args)
        else
          super
        end
      else
        super
      end
    end

    def respond_to?(method)
      if method.to_s.end_with?('_path') or method.to_s.end_with?('_url')
        if main_app.respond_to?(method)
          true
        else
          super
        end
      else
        super
      end
    end
  end
end

app/helpers/badges_engine/badges_helper.rb
module BadgesEngine
  module BadgesHelper
    def show_award(award)
      award.title unless award.nil?
    end

    def show_value(value)
      value.name unless value.nil?
    end

    def show_badge(badge)
      badge.name unless badge.nil?
    end
  end
end

app/views/badges_engine/awards/_award.html.haml
%tr
  %td= award.title
  %td= award.description
  %td= link_to 'Show', award
  %td= link_to 'Edit', edit_award_path(award)
  %td
    = link_to 'Destroy', award, method: :delete,
      data: { confirm: 'Are you sure?' }

app/views/badges_engine/awards/_form.html.haml
= form_for(@award) do |f|
  - if @award.errors.any?
    #error_explanation
      %h2
        = pluralize(@award.errors.count, "error")
        prohibited this @award from being saved:
      %ul
        - @award.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br
    = f.text_field :title
  .field
    = f.label :description
    %br
    = f.text_area :description
  .actions
    = f.submit

app/views/badges_engine/awards/edit.html.haml
%h1 Editing award
= render 'form'
= link_to 'Show', @award
|
= link_to 'Back', awards_path

app/views/badges_engine/awards/index.html.haml
%h1 Listing awards
%table
  %thead
    %tr
      %th Title
      %th Description
      %th
      %th
      %th
  %tbody
    = render @awards
%br
= link_to 'New Award', new_award_path

app/views/badges_engine/awards/new.html.haml
%h1 New award
= render 'form'
= link_to 'Back', awards_path

app/views/badges_engine/awards/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @award.title
%p
  %strong Description:
  = @award.description
= link_to 'Edit', edit_award_path(@award)
|
= link_to 'Back', awards_path

app/views/badges_engine/badges/_badge.html.haml
%tr
  %td= badge.name
  %td= image_tag(badge.image_url)
  %td= badge.description
  %td= show_award(badge.award)
  %td= show_value(badge.value)
  %td= link_to 'Show', badge
  %td= link_to 'Edit', edit_badge_path(badge)
  %td= link_to 'Destroy', badge, method: :delete,
    data: { confirm: 'Are you sure?' }

app/views/badges_engine/badges/_form.html.haml
= simple_form_for(@badge, html: { multipart: true }) do |f|
  = render partial: 'shared/errors', locals: { resource: @badge }
  .col-md-4
    .span4
      = image_tag @badge.image_url
      %section
        %h5 Browse Images
        .field
          = f.input :image, class: 'browse', label: false
  .col-md-8
    .span8
      .field
        = f.input :name
      .field
        = f.input :description
      .field
        = f.input :award_id,
                  collection: BadgesEngine::Award.all,
                  value_method: :id,
                  label_method: :title,
                  prompt: 'Select an Award'
      .field
        = f.input :value_id,
                  collection: BadgesEngine::Value.all,
                  value_method: :id,
                  label_method: :name,
                  prompt: 'Select a Value'
      .field
        = label_tag 'Path:'
        #levels
          = f.simple_fields_for :levels do |level|
            = render 'level_fields', f: level
        .links
          = link_to_add_association '+ Add level', f, :levels
      .actions
        = link_to 'Cancel', badges_path, class: 'btn btn-disabled'
        = f.submit 'Save', class: 'btn'
.clearfix

app/views/badges_engine/badges/edit.html.haml
%h1 Editing badge
= render 'form'
= link_to 'Show', @badge
|
= link_to 'Back', badges_path

app/views/badges_engine/badges/index.html.haml
%h1 Listing badges
%table
  %thead
    %tr
      %th Name
      %th Image
      %th Description
      %th Award
      %th Value
      %th{ colspan: 3 }
    %tbody
      = render @badges
%br
= link_to 'New Badge', new_badge_path

app/views/badges_engine/badges/new.html.haml
%h1 New badge
= render 'form'
= link_to 'Back', badges_path

app/views/badges_engine/badges/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @badge.name
%p
  %strong Image:
  = image_tag(@badge.image_url)
%p
  %strong Description:
  = @badge.description
%p
  %strong Award:
  = show_award(@badge.award)
%p
  %strong Value:
  = show_value(@badge.value)
= link_to 'Edit', edit_badge_path(@badge)
|
= link_to 'Back', badges_path

app/views/badges_engine/levels/_form.html.haml
= form_for(@level) do |f|
  - if @level.errors.any?
    #error_explanation
      %h2
        = pluralize(@level.errors.count, "error")
        prohibited this @level from being saved:
      %ul
        - @level.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :badge_id
    %br
    = f.collection_select :badge_id, BadgesEngine::Badge.all, :id, :name, prompt: 'Select a Badge'
  .field
    = f.label :tier
    %br
    = f.text_field :tier
  .field
    = f.label :badge_alias
    %br
    = f.text_field :badge_alias
  .actions
    = f.submit

app/views/badges_engine/levels/_level.html.haml
%tr
  %td= show_badge(level.badge)
  %td= level.tier
  %td= level.badge_alias
  %td= link_to 'Show', level
  %td= link_to 'Edit', edit_level_path(level)
  %td
    = link_to 'Destroy', level, method: :delete,
      data: { confirm: 'Are you sure?' }

app/views/badges_engine/levels/edit.html.haml
%h1 Editing level
= render 'form'
= link_to 'Show', @level
|
= link_to 'Back', levels_path

app/views/badges_engine/levels/index.html.haml
%h1 Listing levels
%table
  %thead
    %tr
      %th Badge
      %th Tier
      %th Alias
      %th
      %th
  %tbody
    = render @levels
%br
= link_to 'New level', new_level_path

app/views/badges_engine/levels/new.html.haml
%h1 New level
= render 'form'
= link_to 'Back', levels_path

app/views/badges_engine/levels/show.html.haml
%p#notice= notice
%p
  %strong Badge:
  = show_badge(@level.badge)
%p
  %strong Tier:
  = @level.tier
%p
  %strong Alias:
  = @level.badge_alias
= link_to 'Edit', edit_level_path(@level)
|
= link_to 'Back', levels_path

app/views/badges_engine/values/_form.html.haml
= form_for(@value) do |f|
  - if @value.errors.any?
    #error_explanation
      %h2
        = pluralize(@value.errors.count, "error")
        prohibited this value from being saved:
      %ul
        - @value.errors.full_messages.each do |msg|
          %li= msg
  #field
    = f.label :name
    %br
    = f.text_field :name
  #field
    = f.label :description
    %br
    = f.text_area :description
  #actions
    = f.submit

app/views/badges_engine/values/_value.html.haml
%tr
  %td= value.name
  %td= value.description
  %td= link_to 'Show', value
  %td= link_to 'Edit', edit_value_path(value)
  %td
    = link_to 'Destroy', value, method: :delete,
      data: { confirm: 'Are you sure?' }

app/views/badges_engine/values/edit.html.haml
%h1 Editing value
= render 'form'
= link_to 'Show', @value
|
= link_to 'Back', values_path

app/views/badges_engine/values/index.html.haml
%h1 Listing values
%table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th
  %tbody
    = render @values
%br
= link_to 'New Value', new_value_path

app/views/badges_engine/values/new.html.haml
%h1 New value
= render 'form'
= link_to 'Back', values_path

app/views/badges_engine/values/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @value.name
%p
  %strong Description:
  = @value.description
= link_to 'Edit', edit_value_path(@value)
|
= link_to 'Back', values_path

app/views/layouts/dummy.html.haml
= yield